spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./db/tacoCloud
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    name: tacoCloud
    generate-unique-name: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console